/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.ledit;

import org.junit.Test;

import main.java.ledit.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
