/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ledit;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;

public class App {
	
	static final String TEST_FILE = "D:\\my\\ledit\\test.txt";

    public static void main(String[] args) {
    	TextFile someFile = null;
		try {
			someFile = getTextFile(args);
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			System.out.println("CRITICAL ERROR Please secify correct file in UTF8 format");
		}
		if(someFile != null) {
			try {
				CommandReader.processCommands(someFile);
			} catch (IOException e) {
				System.out.println("CRITICAL ERROR during command execution");
			}
		}
        
    }
    
    private static TextFile getTextFile(String[] args) throws IOException {
    	if(args.length > 0) {
    		TextFile someFile = new TextFile(args[0]);
    		if(someFile.exists() && someFile.canRead()) {
    			return someFile;
    		}
    	}
    	
    	System.out.println("ERROR Please secify correct file, using test file for now");
    	//return null;
		return new TextFile(TEST_FILE);
    }
}
